package com.jlpatter.mousejiggler;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MouseJigglerForm {
    private JCheckBox JiggleCheckBox;
    private JPanel panel1;
    private final MouseThread mouseThread;

    public MouseJigglerForm() {
        mouseThread = new MouseThread();

        JiggleCheckBox.addActionListener(event -> {
            if (JiggleCheckBox.isSelected()) {
                mouseThread.start();
            } else {
                mouseThread.stopThread();
            }
        });
    }

    public JPanel getPanel1() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        JiggleCheckBox = new JCheckBox();
        JiggleCheckBox.setSelected(false);
        JiggleCheckBox.setText("Enable Jiggle");
        panel1.add(JiggleCheckBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
